### ISSUE TITLE
[BUG] Docker exec cat on big files

### ISSUE THREAD

**Issue by 0xle0ne** [nxthat/nanocl#115]
Trying to execute both command just produce no output and never end :

```sh
nanocl cargo --namespace system exec proxy -- cat /var/log/nginx/error.log
docker exec system-proxy cat /var/log/nginx/error.log
```

**Comment by mamaicode** [comment]
@leon3s Regarding docker exec system-proxy cat /var/log/nginx/error.log, there could be couple reasons why the command is producing no output and hangs:

1. The container may be unresponsive or has stopped running. Try running docker ps to check the status of the container. 

2. The cat /var/log/nginx/error.log command may be hanging because the log file is not accessible or does not exist. You can check if the file exists within the container by using docker exec to run the command ls /var/log/nginx/. Could be a problem with the nginx installation or configuration.

3.  Perhaps the log is too large to display in console? Try tail.

4. Try docker logs system-proxy if there is an additional error
